name: Feature request
description: Suggest an idea for this project
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem & context
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
