name: CI (placeholder)
on:
  push:
    branches: [ main, dev, "feature/**" ]
  pull_request:
    branches: [ main, dev ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: ls -la
